chore: add initial ci
defenseunicorns/uds-engine pull request #11
Opened 2024-07-10 20:38 UTC by TristanHoladay

Setting up some initial CI and issue templates

2024-07-12 07:11 UTC, jeff-mccoy requested changes
mostly great, just a fe clarifying questions

2024-07-12 07:11 UTC, jeff-mccoy commented on .pre-commit-config.yaml
> +  - repo: https://github.com/sirosen/fix-smartquotes
this is a deprecated repo, that hasnt been touched in 4 yrs, also generally not a fan of brining ing random code like this

2024-07-12 07:11 UTC, jeff-mccoy commented on tasks/test.yaml
> +  - name: stream
not sure i follow the need to break these tests out by package?

2024-07-12 07:11 UTC, jeff-mccoy commented on tasks/setup.yaml
> +            npm install
we should never use `npm i` like this, only `npm ci`, not sure I love the idea of just seeing if node_modules exists, locally this could cause all sorts of interesting problems

2024-07-12 13:48 UTC, TristanHoladay commented on .pre-commit-config.yaml
> +  - repo: https://github.com/sirosen/fix-smartquotes
good call out. we could look to change this in CLI then as well. Probably don't even need it honestly. Looks like[ Zarf ](https://github.com/defenseunicorns/zarf/blob/eca0c530a04c3ed155c03761eb45bd16ba717b79/.pre-commit-config.yaml#L19 ) is using a [newer repo](https://github.com/sirosen/texthooks/blob/9494d633234f89a66d3429f692bc9715e37db1f6/.pre-commit-hooks.yaml#L1) of his to call the same hook.

2024-07-12 13:48 UTC, TristanHoladay commented on tasks/test.yaml
> +  - name: stream
yeah i didn't like that either, I was just having trouble running them together at the time so did that and moved on. but i'll fix that.

2024-07-12 13:55 UTC, TristanHoladay commented on .github/actions/k3d/action.yaml
> +    - run: k3d cluster delete && k3d cluster create --image="rancher/k3s:v1.28.4-k3s2"
oh yeah ... huh, i didn't look at that close enough then. i thought it was just installing k3d. i'll clean that up since we're using slim-dev for e2e anyway.

2024-07-12 14:42 UTC, TristanHoladay commented on .github/workflows/scorecard.yaml
> +          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
ahh yes, we do need that please.

2024-07-12 19:07 UTC, jeff-mccoy commented on tasks/setup.yaml
> +            npm install
in ci none--but if local, you could have an out of date node_modules, think pull down main and there were news deps added or changed, checking will break that

2024-07-12 19:43 UTC, TristanHoladay commented on tasks/setup.yaml
> +            npm install
oh yeah, duh. probably best to just `ci` each time then. shouldn't be that big of an add to the test execution time.

2024-07-13 07:19 UTC, jeff-mccoy approved these changes
awesome job knocking out all this CI setup 🦄

2024-07-13 07:20 UTC, merged